version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${ENV_PROTUBE_DB_USER}
      POSTGRES_PASSWORD: ${ENV_PROTUBE_DB_PWD}
      POSTGRES_DB: ${ENV_PROTUBE_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: protube-app
    environment:
      ENV_PROTUBE_STORE_DIR: /store
      ENV_PROTUBE_DB: ${ENV_PROTUBE_DB}
      ENV_PROTUBE_DB_USER: ${ENV_PROTUBE_DB_USER}
      ENV_PROTUBE_DB_PWD: ${ENV_PROTUBE_DB_PWD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${ENV_PROTUBE_DB}
      SPRING_DATASOURCE_USERNAME: ${ENV_PROTUBE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ENV_PROTUBE_DB_PWD}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    volumes:
      - ${ENV_PROTUBE_STORE_DIR}:/store
    depends_on:
      - db

volumes:
  postgres-data:
