version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${ENV_PROTUBE_DB_USER}
      POSTGRES_PASSWORD: ${ENV_PROTUBE_DB_PWD}
      POSTGRES_DB: ${ENV_PROTUBE_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
